name: build

on:
  workflow_dispatch:

jobs:
  prebuild:
    strategy:
      matrix:
        target-node: [18]
        target-arch: [x86]
    name: Prebuild on Windows x86
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install --ignore-scripts
      - run: choco install nasm
      - run: npx --no-install prebuild -r node -t 18.3.0 --include-regex 'better_sqlite3.node$' --arch ia32 -u ${{ secrets.GITHUB_TOKEN }}  --output prebuilds

      - uses: actions/upload-artifact@v2
        with:
          name: node${{ matrix.target-node }}-windows-${{ matrix.target-arch }}
          path: prebuilds\\*
